[colors.primary]
background = '#191111'
foreground = '#f4e3e2'
 
[colors.cursor]
text = '#f4e3e2'
cursor = '#dac1bf' 
 
[colors.vi_mode_cursor]
text = '#191111'
cursor = '#ffb3af' 
 
[colors.search.matches]
foreground = '#554241' 
background = '#eebe82' 
 
[colors.search.focused_match]
foreground = '#554241' 
background = '#ffb3af' 
 
[colors.footer_bar]
foreground = '#554241' 
background = '#efdfdd' 
 
[colors.hints.start]
foreground = '#554241' 
background = '#f1b9b5' 
 
[colors.hints.end]
foreground = '#554241' 
background = '#f1b9b5' 
 
[colors.selection]
text = '#191111'
background = '#ffb3af'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb3af' 
yellow = '#8f3d3c' 
blue = '#ffb3af' 
magenta = '#eebe82' 
cyan = '#f1b9b5' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
