# : Manager [[[

[mgr]
cwd = { fg = "#f4e3e2" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ffae4f", bg = "#ffae4f" }
marker_cut      = { fg = "#ffddb5", bg = "#ffddb5" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#eebe82", bg = "#eebe82" }

# Count
count_copied   = { fg = "#2a1800", bg = "#ffddb5" }
count_cut      = { fg = "#2a1800", bg = "#ffddb5" }
count_selected = { fg = "#510e11", bg = "#eebe82" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb3af" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb3af", bold = true, bg = "#191111" }
inactive  = { fg = "#f1b9b5", bg = "#191111" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb3af", fg = "#510e11", bold = true }
normal_alt  = { bg = "#554241", fg = "#dac1bf" }

# Select mode
select_main = { bg = "#f1b9b5", fg = "#401e1d", bold = true }
select_alt  = { bg = "#554241", fg = "#dac1bf" }

# Unset mode
unset_main = { bg = "#eebe82", fg = "#3a2300", bold = true }
unset_alt  = { bg = "#554241", fg = "#dac1bf" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#d93f34" }
perm_write = { fg = "#bd751a" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff971c" }
perm_sep   = { fg = "#ff4c3e" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb3af", bg = "#463b3a" }
progress_error  = { fg = "#ffb4ab", bg = "#463b3a" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#463b3a" }
cand = { fg = "#ffb3af" }
rest = { fg = "#510e11" }
desc = { fg = "#f4e3e2" }
separator = " ▶ "
separator_style = { fg = "#f4e3e2" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#eebe82" }
title_warn  = { fg = "#ffb3af" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb3af" }
active = { fg = "#eebe82", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb3af" }
value  = { fg = "#f4e3e2" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb3af", bg = "#510e11" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb3af" }
title   = {}
hovered = { fg = "#ffddb5", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#f4e3e2" }
run    = { fg = "#f4e3e2" }
footer = { fg = "#401e1d", bg = "#f1b9b5" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#c32220" },
    { name = "*", is = "exec", fg = "#ffffff" },

    # Fallback
    { url = "*", fg = "#f4e3e2" },
    { url = "*/", fg = "#ffb3af" },
]

# : ]]]
