#!/usr/bin/env python3
from pathlib import Path
import json

cache = Path.home() / ".cache" / "matugen"
colors_path = cache / "colors.json"
if not colors_path.exists():
    raise SystemExit(f"colors.json missing at {colors_path}")

with colors_path.open() as f:
    data = json.load(f)


def hex_to_rgba(hex_color: str, alpha: float = 1.0) -> str:
    value = hex_color.lstrip("#")
    if len(value) != 6:
        raise ValueError(f"expected 6-digit hex, got {hex_color}")
    r = int(value[0:2], 16)
    g = int(value[2:4], 16)
    b = int(value[4:6], 16)
    return f"rgba({r},{g},{b},{alpha})"


def hex_to_hypr_rgb(hex_color: str) -> str:
    value = hex_color.lstrip("#")
    if len(value) != 6:
        raise ValueError(f"expected 6-digit hex, got {hex_color}")
    return f"rgb({value})"


hypr_lines = [
    "# Generated by apply_matugen_palette.py -- do not edit by hand.",
    "# Import this file from ~/.config/hypr/hyprland.conf",
    "",
    f"$accent         = {hex_to_hypr_rgb(data['primary'])}",
    f"$accent_alt     = {hex_to_hypr_rgb(data['tertiary'])}",
    f"$inactive       = {hex_to_hypr_rgb(data['surface_variant'])}",
]

hypr_file = cache / "hypr.conf"
hypr_file.write_text("\n".join(hypr_lines) + "\n")

waybar_css = f"""/* Generated by apply_matugen_palette.py; import this from ~/.config/waybar/style.css */
* {{
  border: none;
  border-radius: 0;
  font-family: "JetBrainsMono Nerd Font", "Noto Sans", "Cantarell", sans-serif;
  font-size: 10px;
  font-weight: 600;
  min-height: 0;
}}

window#waybar {{
  background: transparent;
  color: {data['on_background']};
}}

.modules-left,
.modules-center,
.modules-right {{
  margin-top: 1px;
}}

#custom-launcher,
#workspaces,
#window,
#tray,
#network,
#pulseaudio,
#backlight,
#battery,
#cpu,
#memory,
#clock,
#custom-power {{
  margin: 0 2px;
  padding: 3px 8px;
  border-radius: 999px;
  color: {data['on_surface']};
  background: {hex_to_rgba(data['surface'], 0.78)};
  border: 1px solid {hex_to_rgba(data['outline'], 0.45)};
}}

#custom-launcher,
#custom-power {{
  font-size: 12px;
  padding: 3px 7px;
}}

#workspaces {{
  padding: 2px 6px;
}}

#workspaces button {{
  color: {data['on_surface_variant']};
  min-width: 24px;
  min-height: 24px;
  margin: 0 3px;
  padding: 0;
  border-radius: 999px;
  background: transparent;
  box-shadow: inset 0 0 0 1px transparent;
  transition: background-color 0.18s ease, color 0.18s ease, box-shadow 0.18s ease;
}}

#workspaces button label {{
  padding: 0;
  min-width: 24px;
}}

#workspaces button.active {{
  color: {data['on_primary']};
  background: {data['primary']};
}}

#workspaces button.urgent {{
  color: {data['on_error']};
  background: {data['error']};
}}

#workspaces button.empty {{
  opacity: 0.82;
}}

#window {{
  padding-left: 8px;
  padding-right: 6px;
}}

#tray {{
  padding-right: 6px;
}}

#battery.warning,
#battery.critical,
#battery.urgent {{
  color: {data['on_error']};
  background: {hex_to_rgba(data['error'], 0.90)};
  border-color: {data['error']};
}}

#pulseaudio.muted {{
  color: {data['on_surface_variant']};
}}

tooltip {{
  background: {data['surface_variant']};
  color: {data['on_surface']};
  border-radius: 12px;
  border: 1px solid {data['outline']};
}}
"""

waybar_file = cache / "waybar.css"
waybar_file.write_text(waybar_css)
