allow_images=false
hide_scroll=true
no_actions=true
term=kitty
mode=dmenu
prompt=Hyprland UI
insensitive=true
allow_markup=true
gtk_dark=true
columns=1
lines=6
matching=fuzzy
sort_order=alphabetical
location=center
width=460
height=260
