#################
### AUTOSTART ###
#################

exec-once = nm-applet &
exec-once = ~/.local/bin/enux-wallpaper-daemon
exec-once = waybar
exec-once = hypridle
exec-once = pkill -x mako || true
exec-once = dunst
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = ~/.local/bin/mic-calibrate-denoise
