#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 2
    gaps_out = 7

    border_size = 2

    col.active_border = $accent $accent_alt 45deg
    col.inactive_border = $inactive

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 14
    rounding_power = 2

    active_opacity = 1
    inactive_opacity = 0.8

    shadow {
        enabled = true
        range = 18
        render_power = 3
        color = rgba(00000055)
    }

    blur {
        enabled = true
        size = 7
        passes = 2
        vibrancy = 0.22
        noise = 0.02
        contrast = 1.05
        brightness = 0.95
    }
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    vfr = true
}
