$mod = SUPER

monitor = ,preferred,auto,1
env = XCURSOR_SIZE,24

exec-once = waybar
exec-once = dunst
exec-once = swaybg -c 1f2933
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle
}

decoration {
    rounding = 8
}

bind = $mod, RETURN, exec, kitty
bind = $mod, D, exec, rofi -show drun
bind = $mod, Q, killactive,
bind = $mod SHIFT, E, exit,
bind = $mod, F, fullscreen,
bind = $mod, V, togglefloating,
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
