---
unpack:
  - source: "/run/archiso/bootmnt/enux/x86_64/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
  - source: "/run/archiso/bootmnt/enux/boot/x86_64/vmlinuz-linux"
    sourcefs: "file"
    destination: "/boot/vmlinuz-linux"
  - source: "/run/archiso/bootmnt/enux/boot/x86_64/initramfs-linux.img"
    sourcefs: "file"
    destination: "/boot/initramfs-linux.img"
